export const strategies = [
  {
    id: 'trend_following',
    name: 'Trend Following',
    markets: 'All',
    complexity: 'Medium',
    holdingPeriod: 'Days-Weeks',
    keyIndicator: 'Moving Averages',
    pnl: 0,
    status: 'active',
    description: "Attempts to capture gains through the analysis of an asset's momentum in a particular direction.",
  },
  {
    id: 'mean_reversion',
    name: 'Mean Reversion',
    markets: 'Equities/Forex',
    complexity: 'Medium',
    holdingPeriod: 'Hours-Days',
    keyIndicator: 'Bollinger Bands',
    pnl: 0,
    status: 'active',
    description: 'Based on the assumption that asset prices and historical returns will revert to the long-run mean.',
  },
  {
    id: 'pairs_trading',
    name: 'Pairs Trading',
    markets: 'Equities',
    complexity: 'High',
    holdingPeriod: 'Days-Weeks',
    keyIndicator: 'Correlation',
    pnl: 0,
    status: 'active',
    description: 'A market-neutral strategy involving matching a long position with a short position in two highly correlated stocks.',
  },
  {
    id: 'arbitrage',
    name: 'Arbitrage',
    markets: 'All',
    complexity: 'High',
    holdingPeriod: 'Seconds-Minutes',
    keyIndicator: 'Price Scanner',
    pnl: 0,
    status: 'active',
    description: 'The simultaneous purchase and sale of an asset to profit from an imbalance in the price.',
  },
  {
    id: 'news_based_trading',
    name: 'News-Based Trading',
    markets: 'All',
    complexity: 'Medium',
    holdingPeriod: 'Minutes-Hours',
    keyIndicator: 'News Sentiment',
    pnl: 0,
    status: 'active',
    description: 'Involves trading based on news announcements and market expectations.',
  },
  {
    id: 'opening_range_breakout',
    name: 'Opening Range Breakout',
    markets: 'Equities',
    complexity: 'Low',
    holdingPeriod: 'Minutes-Hours',
    keyIndicator: 'Price Action',
    pnl: 0,
    status: 'active',
    description: 'Identifies the high and low of a specific period after the market opens to trade breakouts.',
  },
  {
    id: 'gap_and_go',
    name: 'Gap and Go',
    markets: 'Equities',
    complexity: 'Medium',
    holdingPeriod: 'Minutes-Hours',
    keyIndicator: 'Volume Surge',
    pnl: 0,
    status: 'active',
    description: 'Looks for stocks that have a significant price gap up from the previous day\'s close on high volume.',
  },
  {
    id: 'scalping',
    name: 'Scalping',
    markets: 'Forex/Equities',
    complexity: 'Medium',
    holdingPeriod: 'Seconds-Minutes',
    keyIndicator: 'Tick Data',
    pnl: 0,
    status: 'active',
    description: 'A very short-term trading style that aims to profit from small price changes.',
  },
  {
    id: 'abcd_pattern',
    name: 'ABCD Pattern',
    markets: 'All',
    complexity: 'Medium',
    holdingPeriod: 'Minutes-Hours',
    keyIndicator: 'Fibonacci Retracement',
    pnl: 0,
    status: 'active',
    description: 'A classic chart pattern that consists of four points representing a specific sequence of price movements.',
  },
  {
    id: 'bull_flag_bear_flag',
    name: 'Bull Flag / Bear Flag',
    markets: 'All',
    complexity: 'Low',
    holdingPeriod: 'Minutes-Hours',
    keyIndicator: 'Volume',
    pnl: 0,
    status: 'active',
    description: 'A continuation chart pattern that follows a sharp price movement.',
  },
  {
    id: 'top_bottom_reversal',
    name: 'Top/Bottom Reversal',
    markets: 'All',
    complexity: 'Medium',
    holdingPeriod: 'Hours-Days',
    keyIndicator: 'Candlestick Patterns',
    pnl: 0,
    status: 'active',
    description: 'A strategy to trade against the prevailing trend at key support or resistance levels.',
  },
  {
    id: 'moving_average_trend',
    name: 'Moving Average Trend',
    markets: 'All',
    complexity: 'Low',
    holdingPeriod: 'Days-Weeks',
    keyIndicator: 'Moving Averages (SMA/EMA)',
    pnl: 0,
    status: 'active',
    description: 'Uses moving averages to identify the direction of the trend for entries and exits.',
  },
  {
    id: 'vwap_trading',
    name: 'VWAP Trading',
    markets: 'Equities',
    complexity: 'Medium',
    holdingPeriod: 'Minutes-Hours',
    keyIndicator: 'VWAP',
    pnl: 0,
    status: 'active',
    description: 'Uses the Volume-Weighted Average Price (VWAP) as a key indicator for intraday entries and exits.',
  },
  {
    id: 'support_and_resistance',
    name: 'Support and Resistance',
    markets: 'All',
    complexity: 'Low',
    holdingPeriod: 'Hours-Days',
    keyIndicator: 'Price Levels',
    pnl: 0,
    status: 'active',
    description: 'Trades based on historical price levels that act as floors (support) or ceilings (resistance).',
  },
  {
    id: 'red_to_green_move',
    name: 'Red to Green Move',
    markets: 'Equities',
    complexity: 'Low',
    holdingPeriod: 'Minutes-Hours',
    keyIndicator: 'Price Action',
    pnl: 0,
    status: 'active',
    description: 'An intraday strategy focusing on stocks that move from a negative (red) to a positive (green) price on the day.',
  },
  {
    id: 'momentum_strategy',
    name: 'Momentum Strategy',
    markets: 'All',
    complexity: 'Medium',
    holdingPeriod: 'Days-Weeks',
    keyIndicator: 'Rate of Change (ROC)',
    pnl: 0,
    status: 'active',
    description: 'Focuses on the rate of price change, buying assets that are accelerating in price.',
  },
  {
    id: 'volatility_breakout',
    name: 'Volatility Breakout',
    markets: 'All',
    complexity: 'Medium',
    holdingPeriod: 'Hours-Days',
    keyIndicator: 'Bollinger Bands Width',
    pnl: 0,
    status: 'active',
    description: 'Trades on assets breaking out from a period of low volatility, anticipating a significant price move.',
  },
  {
    id: 'sentiment_analysis',
    name: 'Sentiment Analysis',
    markets: 'All',
    complexity: 'High',
    holdingPeriod: 'Minutes-Days',
    keyIndicator: 'Sentiment Scores',
    pnl: 0,
    status: 'active',
    description: 'Uses quantified sentiment data from news, social media, or other sources to predict price movements.',
  },
  {
    id: 'market_making',
    name: 'Market Making',
    markets: 'All',
    complexity: 'Very High',
    holdingPeriod: 'Seconds-Minutes',
    keyIndicator: 'Order Book',
    pnl: 0,
    status: 'active',
    description: 'A high-frequency strategy that profits by providing liquidity and capturing the bid-ask spread.',
  },
  {
    id: 'automated_portfolio_rebalancing',
    name: 'Automated Portfolio Rebalancing',
    markets: 'All',
    complexity: 'Low',
    holdingPeriod: 'Weeks-Months',
    keyIndicator: 'Asset Allocation',
    pnl: 0,
    status: 'active',
    description: 'An automated strategy to maintain a target asset allocation by periodically buying or selling assets.',
  },
];
