export const strategies = [
  {
    id: 'trendfollowing',
    name: 'Trend Following',
    markets: 'All',
    complexity: 'Medium',
    holdingPeriod: 'Days-Weeks',
    keyIndicator: 'Moving Averages',
    pnl: 5000,
    status: 'active',
    description: 'A strategy that attempts to capture gains through the analysis of an asset\'s momentum in a particular direction. The strategy involves buying an asset that is in an uptrend and selling it when it reverses.',
  },
  {
    id: 'meanreversion',
    name: 'Mean Reversion',
    markets: 'Equities/Forex',
    complexity: 'Medium',
    holdingPeriod: 'Hours-Days',
    keyIndicator: 'Bollinger Bands',
    pnl: -1500,
    status: 'inactive',
    description: 'This strategy is based on the assumption that asset prices and historical returns will revert to the long-run mean. The strategy involves buying an asset when its price is significantly below the mean and selling it when it is significantly above.',
  },
  {
    id: 'pairsstrading',
    name: 'Pairs Trading',
    markets: 'Equities',
    complexity: 'High',
    holdingPeriod: 'Days-Weeks',
    keyIndicator: 'Correlation',
    pnl: 2500,
    status: 'active',
    description: 'A market-neutral strategy that involves matching a long position with a short position in two stocks with a high correlation. The strategy profits from the temporary breakdown in the correlation.',
  },
  {
    id: 'arbitrage',
    name: 'Arbitrage',
    markets: 'All',
    complexity: 'High',
    holdingPeriod: 'Seconds-Minutes',
    keyIndicator: 'Price Scanner',
    pnl: 1000,
    status: 'active',
    description: 'The simultaneous purchase and sale of an asset to profit from an imbalance in the price. This is a risk-free strategy that requires speed and advanced technology to execute.',
  },
  {
    id: 'newsbasedtrading',
    name: 'News-Based Trading',
    markets: 'All',
    complexity: 'Medium',
    holdingPeriod: 'Minutes-Hours',
    keyIndicator: 'News Sentiment',
    pnl: 0,
    status: 'active',
    description: 'This strategy involves trading based on news announcements and market expectations. The strategy aims to profit from the market\'s reaction to news events.',
  },
  {
    id: 'openingrangebreakout',
    name: 'Opening Range Breakout',
    markets: 'Equities',
    complexity: 'Low',
    holdingPeriod: 'Minutes-Hours',
    keyIndicator: 'Price Action',
    pnl: 0,
    status: 'active',
    description: 'This strategy identifies the high and low of a specific period after the market opens (the opening range). A buy order is placed if the price breaks above the opening range high, and a sell order is placed if it breaks below the opening range low.',
  },
  {
    id: 'gapandgo',
    name: 'Gap and Go',
    markets: 'Equities',
    complexity: 'Medium',
    holdingPeriod: 'Minutes-Hours',
    keyIndicator: 'Volume Surge',
    pnl: 2750,
    status: 'active',
    description: 'This strategy looks for stocks that have a significant price gap up from the previous day\'s close on high volume. The strategy assumes that the momentum will continue in the same direction.',
  },
  {
    id: 'scalping',
    name: 'Scalping',
    markets: 'Forex',
    complexity: 'Medium',
    holdingPeriod: 'Seconds-Minutes',
    keyIndicator: 'Tick Data',
    pnl: 4800,
    status: 'active',
    description: 'Scalping is a very short-term trading style that aims to profit from small price changes. Scalpers execute a large number of trades in a single day.',
  },
  {
    id: 'abcdpattern',
    name: 'ABCD Pattern',
    markets: 'Equities',
    complexity: 'Medium',
    holdingPeriod: 'Minutes-Hours',
    keyIndicator: 'Fibonacci Retracement',
    pnl: 0,
    status: 'active',
    description: 'A classic chart pattern that consists of four points (A, B, C, and D) that represent a specific sequence of price movements. The pattern can be used to identify potential buying or selling opportunities.',
  },
];
